# Generated by Django 6.0.5 on 2026-05-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='category',
            field=models.CharField(choices=[('it', 'Information Technology'), ('finance', 'Finance & Accounting'), ('health', 'Health & Medicine'), ('education', 'Education & Training'), ('engineering', 'Engineering'), ('marketing', 'Marketing & Communication'), ('law', 'Law & Legal Services'), ('hr', 'Human Resources'), ('sales', 'Sales & Business Development'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='experience_level',
            field=models.CharField(choices=[('junior', 'Junior (0-2 years)'), ('mid', 'Mid-level (2-5 years)'), ('senior', 'Senior (5+ years)'), ('any', 'Any Level')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='job_photos/'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='positions_available',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('contract', 'Contract')], default='full_time', max_length=20),
        ),
    ]
