# Generated by Django 6.0.5 on 2026-05-28 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joboffer_category_joboffer_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentmessage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jobs.application'),
        ),
    ]
